sudo: required
services:
  - docker

before_install:
  - docker build -t vong/docker-react -f Dockerfile.dev .

script:
  - docker run vong/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-192540139408"
  bucker_folder: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_id:
    secure: "$AWS_SECRET_KEY"
